name: Bug Report
description: File a bug report to help us improve updep
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'updep' in directory...
        2. Select package...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: Instead...
    validations:
      required: true

  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      description: Which package manager are you using?
      options:
        - npm
        - yarn
        - pnpm
        - bun
        - Other
    validations:
      required: true

  - type: input
    id: package-manager-version
    attributes:
      label: Package Manager Version
      description: Run `npm --version`, `yarn --version`, etc.
      placeholder: e.g., 10.2.3
    validations:
      required: true

  - type: input
    id: updep-version
    attributes:
      label: updep Version
      description: Run `updep --version`
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: e.g., macOS 14.0, Ubuntu 22.04, Windows 11
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: Please paste any relevant logs or error messages
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here (screenshots, package.json contents, etc.)
